name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  TERM: xterm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: '**/*.csproj'
      - name: Restore dependencies
        run: dotnet restore DotnetLegacyMigrator.sln
      - name: Build
        run: dotnet build DotnetLegacyMigrator.sln --no-restore -c Release
      - name: Test
        run: dotnet test DotnetLegacyMigrator.sln --no-build -c Release --logger "console;verbosity=normal"
